export const CHANGE_FIRST_NAME = 'CHANGE_FIRST_NAME';
export const CHANGE_LAST_NAME = 'CHANGE_LAST_NAME';
export const CHANGE_SEX = 'CHANGE_SEX';
export const CHANGE_LOYALTY_PROGRAMM = 'CHANGE_LOYALTY_PROGRAMM';
export const CHANGE_CARD_NUMBER = 'CHANGE_CARD_NUMBER';
export const SET_RANDOM_DATA = 'SET_RANDOM_DATA';
export const VALIDATION = 'VALIDATION';
